// src/index.js  —  Cloudflare Workers variant
// Generated by streamx-deploy init --platform cloudflare
//
// Cloudflare Workers doesn't use Node.js or Express.
// It uses the standard Web Request/Response API.
// ─────────────────────────────────────────────────────────────────────────────

export default {
  async fetch(request, env, ctx) {
    const url    = new URL(request.url)
    const path   = url.pathname
    const method = request.method

    const cors = {
      'Access-Control-Allow-Origin':  '*',
      'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS',
      'Access-Control-Allow-Headers': '*',
    }

    if (method === 'OPTIONS') return new Response(null, { headers: cors })

    // ── /manifest.json ────────────────────────────────────────────────────────
    if (path === '/manifest.json') return jsonResponse(getManifest(env), cors)

    // ── /stream/{type}/{id}.json ──────────────────────────────────────────────
    const streamMatch = path.match(/^\/stream\/([^/]+)\/(.+)\.json$/)
    if (streamMatch) {
      const [, type, rawId] = streamMatch
      const id = decodeURIComponent(rawId)
      const [imdbId, season, episode] = id.split(':')
      const streams = await getStreams(type, imdbId, season, episode, env)
      return jsonResponse({ streams }, cors)
    }

    // ── /subtitles/{type}/{id}.json ───────────────────────────────────────────
    const subMatch = path.match(/^\/subtitles\/([^/]+)\/(.+)\.json$/)
    if (subMatch) {
      const [, type, rawId] = subMatch
      const subtitles = await getSubtitles(type, decodeURIComponent(rawId), env)
      return jsonResponse({ subtitles }, cors)
    }

    // ── /catalog/{type}/{id}.json ─────────────────────────────────────────────
    const catMatch = path.match(/^\/catalog\/([^/]+)\/([^/]+)\.json$/)
    if (catMatch) {
      const [, type, id] = catMatch
      const metas = await getCatalog(type, id, url.searchParams, env)
      return jsonResponse({ metas }, cors)
    }

    // ── / home page ───────────────────────────────────────────────────────────
    if (path === '/') {
      const manifest    = getManifest(env)
      const manifestUrl = `${url.origin}/manifest.json`
      return new Response(homePage(manifest, manifestUrl), {
        headers: { ...cors, 'Content-Type': 'text/html; charset=utf-8' }
      })
    }

    // ── /health ───────────────────────────────────────────────────────────────
    if (path === '/health') return jsonResponse({ status: 'ok' }, cors)

    return new Response('Not Found', { status: 404, headers: cors })
  }
}

// ─────────────────────────────────────────────────────────────────────────────
//  Manifest  (reads from env vars set in wrangler.toml or Cloudflare dashboard)
// ─────────────────────────────────────────────────────────────────────────────
function getManifest(env) {
  return {
    id:          env.ADDON_ID      ?? 'community.myname.myaddon',
    version:     env.ADDON_VERSION ?? '1.0.0',
    name:        env.ADDON_NAME    ?? 'My StreamX Addon',
    description: env.ADDON_DESC   ?? 'Community addon for StreamX',
    logo:        env.ADDON_LOGO   ?? '',
    types:       ['movie', 'series'],
    resources:   ['stream'],
    idPrefixes:  ['tt'],
    catalogs:    [],
  }
}

// ─────────────────────────────────────────────────────────────────────────────
//  !! EDIT THESE FUNCTIONS with your actual logic !!
// ─────────────────────────────────────────────────────────────────────────────
async function getStreams(type, imdbId, season, episode, env) {
  // env.MY_API_KEY  ← set with: wrangler secret put MY_API_KEY
  //
  // Example:
  // const resp = await fetch(`https://mysite.xyz/api?imdb=${imdbId}`, {
  //   headers: { 'User-Agent': 'StreamX/1.0' }
  // })
  // const data = await resp.json()
  // return data.streams.map(s => ({ url: s.link, name: s.quality }))

  return []
}

async function getSubtitles(type, id, env) {
  return []
}

async function getCatalog(type, id, params, env) {
  return []
}

// ─────────────────────────────────────────────────────────────────────────────
//  Helpers
// ─────────────────────────────────────────────────────────────────────────────
function jsonResponse(data, headers = {}) {
  return new Response(JSON.stringify(data), {
    headers: { 'Content-Type': 'application/json', ...headers }
  })
}

function homePage(m, manifestUrl) {
  return `<!DOCTYPE html><html><head><title>${m.name}</title>
<style>body{font-family:sans-serif;max-width:600px;margin:60px auto;background:#06060f;color:#fff;padding:24px}
h1{color:#82b1ff}.btn{display:inline-block;padding:12px 24px;background:#1a3a1a;color:#81c784;
border:1px solid #4caf50;border-radius:8px;text-decoration:none;font-weight:bold;margin-top:12px}
pre{background:#0e0e18;padding:16px;border-radius:8px}</style></head>
<body><h1>${m.name}</h1><p>${m.description}</p>
<pre>${manifestUrl}</pre>
<a class="btn" href="streamx://install-addon?url=${encodeURIComponent(manifestUrl)}">➕ Install in StreamX</a>
</body></html>`
}
