// src/index.js  —  StreamX Addon Template
// Generated by streamx-deploy init
//
// This template works on ALL platforms:
//   Cloudflare Workers, Vercel, Render, Railway, Docker/VPS
// ─────────────────────────────────────────────────────────────────────────────

import express from 'express'
import cors    from 'cors'

const app  = express()
const port = parseInt(process.env.PORT ?? '7000')

// CORS — required by StreamX + Stremio
app.use(cors())
app.use(express.json())

// ── Manifest ──────────────────────────────────────────────────────────────────
const MANIFEST = {
  id:          process.env.ADDON_ID      ?? 'community.myname.myaddon',
  version:     process.env.ADDON_VERSION ?? '1.0.0',
  name:        process.env.ADDON_NAME    ?? 'My StreamX Addon',
  description: process.env.ADDON_DESC   ?? 'Community addon for StreamX',
  logo:        process.env.ADDON_LOGO   ?? '',
  types:       ['movie', 'series'],
  resources:   ['stream'],
  idPrefixes:  ['tt'],
  catalogs:    [],
}

app.get('/manifest.json', (req, res) => res.json(MANIFEST))

// ── Stream handler ────────────────────────────────────────────────────────────
// !! EDIT THIS FUNCTION with your actual scraping / API logic !!
app.get('/stream/:type/:id.json', async (req, res) => {
  const { type, id } = req.params
  const decodedId    = decodeURIComponent(id)
  // id formats:
  //   movie  → "tt1234567"
  //   series → "tt1234567:1:3"   (imdbId:season:episode)
  const [imdbId, season, episode] = decodedId.split(':')

  try {
    const streams = await getStreams(type, imdbId, season, episode)
    res.json({ streams })
  } catch (e) {
    console.error('[stream] error:', e.message)
    res.json({ streams: [] })
  }
})

// ── Subtitle handler (optional) ───────────────────────────────────────────────
// Remove this route if you don't need subtitles.
// If keeping it, add "subtitles" to MANIFEST.resources above.
app.get('/subtitles/:type/:id.json', async (req, res) => {
  const { type, id } = req.params
  try {
    const subtitles = await getSubtitles(type, decodeURIComponent(id))
    res.json({ subtitles })
  } catch (e) {
    res.json({ subtitles: [] })
  }
})

// ── Catalog handler (optional) ────────────────────────────────────────────────
// Remove if you only provide streams.
// If keeping it, add a catalog entry to MANIFEST.catalogs above.
app.get('/catalog/:type/:id.json', async (req, res) => {
  const { type, id } = req.params
  const search = req.query.search
  try {
    const metas = await getCatalog(type, id, search)
    res.json({ metas })
  } catch (e) {
    res.json({ metas: [] })
  }
})

// ── Health check ──────────────────────────────────────────────────────────────
app.get('/health', (req, res) => res.json({ status: 'ok', version: MANIFEST.version }))

// ── Home page ─────────────────────────────────────────────────────────────────
app.get('/', (req, res) => {
  const manifestUrl = `${req.protocol}://${req.get('host')}/manifest.json`
  res.send(`<!DOCTYPE html>
<html><head><title>${MANIFEST.name}</title>
<style>body{font-family:sans-serif;max-width:600px;margin:60px auto;background:#06060f;color:#fff;padding:24px}
h1{color:#82b1ff}.btn{display:inline-block;padding:12px 24px;background:#1a3a1a;color:#81c784;
border:1px solid #4caf50;border-radius:8px;text-decoration:none;font-weight:bold;margin-top:12px}
pre{background:#0e0e18;padding:16px;border-radius:8px;overflow-x:auto}</style>
</head><body>
<h1>${MANIFEST.name}</h1>
<p>${MANIFEST.description}</p>
<p>Types: ${MANIFEST.types.join(', ')} · Resources: ${MANIFEST.resources.join(', ')}</p>
<h3>Install in StreamX</h3>
<pre>${manifestUrl}</pre>
<a class="btn" href="streamx://install-addon?url=${encodeURIComponent(manifestUrl)}">➕ Install in StreamX</a>
<p><small>Also compatible with Stremio</small></p>
</body></html>`)
})

// ─────────────────────────────────────────────────────────────────────────────
//  YOUR LOGIC — edit these functions
// ─────────────────────────────────────────────────────────────────────────────

async function getStreams(type, imdbId, season, episode) {
  // !! REPLACE WITH YOUR SCRAPING / API LOGIC !!
  //
  // Examples of what to do here:
  //   - Fetch from a website using fetch() + parse HTML
  //   - Call a third-party API
  //   - Scrape stream links
  //
  // Return format:
  //   { url, name, description, behaviorHints? }
  //
  // Example:
  // const resp = await fetch(`https://mysite.xyz/api?imdb=${imdbId}`)
  // const data = await resp.json()
  // return data.streams.map(s => ({ url: s.link, name: s.quality, description: s.server }))

  return [
    // Remove this placeholder and add real streams:
    {
      url:         'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
      name:        'Sample 720p',
      description: `${imdbId} | Template Addon`,
    }
  ]
}

async function getSubtitles(type, id) {
  // Return: [{ url, lang, id }]
  return []
}

async function getCatalog(type, id, search) {
  // Return: [{ id, type, name, poster, description }]
  return []
}

// ─────────────────────────────────────────────────────────────────────────────
app.listen(port, () => {
  console.log(`\n🚀 ${MANIFEST.name} running on port ${port}`)
  console.log(`   Manifest: http://127.0.0.1:${port}/manifest.json`)
  console.log(`   Test:     streamx-deploy test\n`)
})

export default app   // for Vercel serverless
